In [4]:
image_path = "D:\\01_STUST Course Information\\Codes\\Database\\Image\\"

In [1]:
import cv2
import numpy as np

src = np.zeros((7,7),np.uint8) 
src[1:6,1:6] = 1                    # 建立前景影像
kernel = np.ones((3,3),np.uint8)    # 建立內核
dst = cv2.erode(src, kernel)        # 腐蝕操作
print(f"src = \n {src}")
print(f"kernel = \n {kernel}")
print(f"Erosion = \n {dst}")

src = 
 [[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
kernel = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Erosion = 
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
import cv2
import numpy as np

src = cv2.imread(image_path + "bw.jpg")
kernel = np.ones((5, 5),np.uint8)       # 建立5x5內核
dst1 = cv2.erode(src, kernel)           # 腐蝕操作
kerne2 = np.ones((11, 11),np.uint8)     # 建立11x11內核
dst2 = cv2.erode(src, kerne2)           # 腐蝕操作

cv2.imshow("src",src)
cv2.imshow("after erosion 5 x 5",dst1)
cv2.imshow("after erosion 11 x 11",dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

src = cv2.imread(image_path + "bw_noise.jpg")
kernel = np.ones((3,3),np.uint8)        # 建立3x3內核
dst1 = cv2.erode(src, kernel)           # 腐蝕操作
kerne2 = np.ones((5,5),np.uint8)        # 建立5x5內核
dst2 = cv2.erode(src, kerne2)           # 腐蝕操作

cv2.imshow("src",src)
cv2.imshow("after erosion 3 x 3",dst1)
cv2.imshow("after erosion 5 x 5",dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
import cv2
import numpy as np

src = cv2.imread(image_path + "whilster.jpg")
kernel = np.ones((3,3),np.uint8)        # 建立3x3內核
dst1 = cv2.erode(src, kernel)           # 腐蝕操作
kerne2 = np.ones((5,5),np.uint8)        # 建立5x5內核
dst2 = cv2.erode(src, kerne2)           # 腐蝕操作

cv2.imshow("src",src)
cv2.imshow("after erosion 3 x 3",dst1)
cv2.imshow("after erosion 5 x 5",dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()